import "./assets/fonts/Montserrat-VariableFont_wght.ttf";
import { MediaPlayer } from "./modules/mediaplayer.slint";
import { Navbar } from "./modules/navbar.slint";
import { HomePage, SongData } from "./pages/home.slint";
import { MusicPage } from "./pages/music.slint";

import { NotFoundPage } from "./pages/not_found.slint";

export component AppWindow inherits Window {
    title: "ShrimpMusic";
    icon: @image-url("assets/Logo.png");
    default-font-family: "Montserrat";
    width: 920px;
    height: 600px;
    background: #FFFFFF;
    
    property <bool> music-sidebar-open: false;
    property <int> music-sidebar-view: 0;

    in-out property <[SongData]> recent-songs: [
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
        { title: "Unknown Music", artist: "Unknown Artist", album-art: @image-url("./assets/Music Unknown.png") },
    ];
    VerticalLayout {
        padding-left: 15px;
        padding-top: 15px;
        padding-right: 15px;
        padding-bottom: 15px;
        spacing: 12px;

        // Navbar & Main Content
        HorizontalLayout {
            spacing: 12px;
            vertical-stretch: 1;

            navbar := Navbar { }

            if (navbar.active-tab == 2) : home-page := HomePage {
                recent-songs: root.recent-songs;
            }
            if (navbar.active-tab == 3) : MusicPage {
                sidebar-open <=> root.music-sidebar-open;
                sidebar-view <=> root.music-sidebar-view;
            }
            if (navbar.active-tab != 2 && navbar.active-tab != 3) : NotFoundPage {
                go-home => { navbar.active-tab = 2; }
            }
        }

        // Media Player (bottom)
        MediaPlayer {
            queue-clicked => {
                if (navbar.active-tab != 3) {
                    navbar.active-tab = 3;
                }
                root.music-sidebar-open = true;
                root.music-sidebar-view = 1;
            }
            lyrics-clicked => {
                if (navbar.active-tab != 3) {
                    navbar.active-tab = 3;
                }
                root.music-sidebar-open = true;
                root.music-sidebar-view = 2;
            }
        }
    }
}
