import "./assets/fonts/Montserrat-VariableFont_wght.ttf";
import { MediaPlayer } from "./modules/mediaplayer.slint";
import { Navbar } from "./modules/navbar.slint";
import { HomePage, SongData } from "./pages/home.slint";

export component AppWindow inherits Window {
    title: "ShrimpMusic";
    icon: @image-url("assets/Logo.png");
    default-font-family: "Montserrat";
    width: 920px;
    height: 600px;
    background: #FFFFFF;

    // Property untuk diisi dari Rust backend
    in-out property <[SongData]> recent-songs <=> home-page.recent-songs;
    VerticalLayout {
        padding-left: 15px;
        padding-top: 15px;
        padding-right: 15px;
        padding-bottom: 15px;
        spacing: 12px;

        // Navbar + Main Content (side by side)
        HorizontalLayout {
            spacing: 12px;
            vertical-stretch: 1;

            Navbar { }

            home-page := HomePage { }
        }

        // Media Player (bottom)
        MediaPlayer { }
    }
}
