import "./assets/fonts/Montserrat-VariableFont_wght.ttf";
import { MediaPlayer } from "./modules/mediaplayer.slint";
import { Navbar } from "./modules/navbar.slint";

export component AppWindow inherits Window {
    title: "ShrimpMusic";
    icon: @image-url("assets/Logo.png");
    default-font-family: "Montserrat";
    width: 920px;
    height: 600px;
    background: #FFFFFF;

     // Default tab (misal: 2 = Home)

    VerticalLayout {
        padding-left: 15px;
        padding-top: 15px;
        padding-right: 15px;
        padding-bottom: 15px;

        spacing: 12px;
        // Navbar
        Navbar{}

        HorizontalLayout {
        // Main Content
        HorizontalLayout { }
        }
        // Media Player
        MediaPlayer {}
    }
}
